# Generated by Django 3.1.7 on 2021-06-13 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210612_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('<django.db.models.query_utils.DeferredAttribute object at 0x000002CBBCEC9940>', '<django.db.models.query_utils.deferredattribute object at 0x000002cbbcec9940>')], default='<django.db.models.query_utils.DeferredAttribute object at 0x000002CBBCEC9940>', max_length=200)),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.post')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
