# Generated by Django 3.1.7 on 2021-06-13 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(choices=[('<django.db.models.query_utils.DeferredAttribute object at 0x000001E3798CFBE0>', '<django.db.models.query_utils.deferredattribute object at 0x000001e3798cfbe0>')], default='<django.db.models.query_utils.DeferredAttribute object at 0x000001E3798CFBE0>', max_length=200),
        ),
    ]
