# Generated by Django 3.1.7 on 2021-06-13 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210614_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(choices=[('<django.db.models.query_utils.DeferredAttribute object at 0x0000019FFAE3FBA8>', '<django.db.models.query_utils.deferredattribute object at 0x0000019ffae3fba8>')], default='<django.db.models.query_utils.DeferredAttribute object at 0x0000019FFAE3FBA8>', max_length=200),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.post'),
        ),
    ]
